# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: chapiter
description: >
 
keywords: []

author:
    name: Jaki Chen
    email: cc@chapiter.cc

baseurl: "" # the subpath of your site, e.g. /blog
url: #"https://chapiter.cc" # the base hostname & protocol for your site, e.g. http://example.com

# Site Config
blog:
    name: chapiter
    google_analytics: "UA-166822615-2"
    last_modified_at: 2020-06-15 12:58:30


# Collections
collections:
    careers:
        output              : true
    perspectives:
        output              : true
    projects:
        output              : true

collections_dir             : src

# Compress CSS
sass:
    style: compressed

# Build settings
theme: minima
plugins:
    - jekyll-feed
    - jekyll-sitemap
    # - airtable
    # - bigdecimal
    # - activesupport
    # - json
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
social:
    name: chapiter
    links:
        - '"https://behance.net/Chapiter"'
        - '"https://www.linkedin.com/in/Chapiter"'
        - '"https://github.com/Chapiter"'
        - '"https://behance.net/Chapiter"'

webmaster_verifications:
    google: google
    bing: bing
    alexa: alexa
    yandex: yandex
    baidu: baidu

# Cmopress html
compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    ignore:
        envs: [local]
    blanklines: false
    profile: false
    startings: [html, head, body]
#
